### ISSUE TITLE
Add flag to enable tracking in preview mode

### ISSUE THREAD

**Issue by OPesicka** [RBND-studio/flows-js#207]
We currently disable tracking in preview mode to avoid sending "irrelevant" data to analytics tools. Let's add a flag that would enable it so devs can test out the implementation before going to production.

While at it let's also add `stepID` to the tracking function.

**Comment by chindnguyen** [comment]
This update will be very helpful, I am waiting for testing it out

**Comment by OPesicka** [comment]
Let's also add:

event type ("startFlow" | "nextStep" | "prevStep" | "finishFlow" | "cancelFlow")
