### ISSUE TITLE
Possibility to use in intranet (without internet connection)

### ISSUE THREAD

**Issue by mubinahmed** [RBND-studio/flows-js#71]
This looks to be an awesome library. 
I would like to know if it is possible to use in enterprise envrionments where there is no internet connection? I see a `projectId` being used as part of initialization. Does that connect to your servers for any validations/license checks?

**Comment by VojtechVidra** [comment]
Yes, this library can be used completely standalone without using `projectId`. It will not be making any network requests. And it is licensed as MIT, so you can use it completely free.

Currently our main focus is on offering the best user and developer experience when using this library with our SaaS solution: https://flows.sh. Hence you won't find much information about how to use it in our documentation. We may put more effort into making this better for people using the library standalone in the future.

To use this library standalone just change your import from `@flows/js` to `@flows/js/core`, for example: `import { init, startFlow } from "@flows/js/core"`. And most of the methods are decently documented with TSDoc. Using it with TypeScript will also help you a lot when defining the flow steps.
